apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple component
  description: An example of a Backstage application.
spec:
  type: website
  owner: user:default/varshajeevan123
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-post-api
  description: Sample API for a post method
  tags:
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: user:default/varshajeevan123
  definition: |
    openapi: 3.0.0
    info:
      title: Demo Post API
      version: 1.0.0
    servers:
      - url: https://jsonplaceholder.typicode.com
    paths:
      /posts:
        post:
          summary: Create a new post
          operationId: createPost
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    title:
                      type: string
                    body:
                      type: string
                    userId:
                      type: integer
          responses:
            "201":
              description: Created
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: software-documentation
  description: Documentation for Developer.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:default/varshajeevan123

