apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: astra-api
  description: Astra API Swagger documentation
spec:
  type: openapi
  lifecycle: production
  owner: engineering
  definition:
    $text: ./astra-api.yaml